name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compress
        run: tar -zcvf trivy-bitbucket.tar.gz bitbucket.py plugin.yaml LICENSE
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            trivy-bitbucket.tar.gz
